### ISSUE TITLE
Doesn't work with JDK 8

### ISSUE THREAD

**Issue by andrewswan** [cristianonicolai/jira-jacoco-example#1]
Here's what I get when I run `mvn clean verify`:
```...
[INFO] [talledLocalContainer] 2020-02-13 14:58:40,155 [         localhost-startStop-1] DatabaseLauncher               WARN  
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] ******************************************************************************************
[INFO] [talledLocalContainer] hsqldb is an in-memory database, and susceptible to corruption when abnormally terminated.
[INFO] [talledLocalContainer] DO NOT USE IN PRODUCTION, please switch to a regular database.
[INFO] [talledLocalContainer] ******************************************************************************************
[INFO] [talledLocalContainer] 
[INFO] [talledLocalContainer] 2020-02-13 14:58:40,180 [         localhost-startStop-1] PluginDiagnostics              WARN  Registering PluginDiagnostics with the event manager.
[INFO] [talledLocalContainer] 2020-02-13 14:58:43,001 [               FelixStartLevel] FelixOsgiContainerManager      ERROR Error starting file:/Users/aswan/projects/third-party/jira-jacoco-example/target/jira/home/plugins/.osgi-plugins/framework-bundles/spring-osgi-extender-1.2.1.jar
[INFO] [talledLocalContainer] java.lang.IllegalStateException: Cannot create ConcurrentHashMap - neither JDK 1.5 nor backport-concurrent available on the classpath
[INFO] [talledLocalContainer] 	at org.springframework.core.CollectionFactory.createConcurrentMap(CollectionFactory.java:229)
[INFO] [talledLocalContainer] 	at org.springframework.osgi.extender.internal.activator.ContextLoaderListener.<init>(ContextLoaderListener.java:332)
[INFO] [talledLocalContainer] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO] [talledLocalContainer] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO] [talledLocalContainer] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO] [talledLocalContainer] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[INFO] [talledLocalContainer] 	at java.lang.Class.newInstance(Class.java:442)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:3659)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1812)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.startBundle(Felix.java:1734)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1143)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
[INFO] [talledLocalContainer] 	at java.lang.Thread.run(Thread.java:748)
[INFO] [talledLocalContainer] 2020-02-13 14:58:43,001 [            FelixDispatchQueue] FelixOsgiContainerManager      ERROR Framework error in bundle org.springframework.osgi.extender
[INFO] [talledLocalContainer] org.osgi.framework.BundleException: Activator start error in bundle org.springframework.osgi.extender [5].
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1864)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.startBundle(Felix.java:1734)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1143)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
[INFO] [talledLocalContainer] 	at java.lang.Thread.run(Thread.java:748)
[INFO] [talledLocalContainer] Caused by: java.lang.IllegalStateException: Cannot create ConcurrentHashMap - neither JDK 1.5 nor backport-concurrent available on the classpath
[INFO] [talledLocalContainer] 	at org.springframework.core.CollectionFactory.createConcurrentMap(CollectionFactory.java:229)
[INFO] [talledLocalContainer] 	at org.springframework.osgi.extender.internal.activator.ContextLoaderListener.<init>(ContextLoaderListener.java:332)
[INFO] [talledLocalContainer] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO] [talledLocalContainer] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO] [talledLocalContainer] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO] [talledLocalContainer] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[INFO] [talledLocalContainer] 	at java.lang.Class.newInstance(Class.java:442)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:3659)
[INFO] [talledLocalContainer] 	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1812)
[INFO] [talledLocalContainer] 	... 4 more
...
```
... and then all the plugins fail to load, and Jira fails to respond at `http://<my_host>:2990/jira`. Is there any chance you could please upgrade this project to recent (supported) versions of things, e.g.:
* Java: ⇒ 1.8
* Jira: ⇒ 8.7.1 (or check [here](https://www.atlassian.com/software/jira/download))
* testkit.version: ⇒ 8.1.14 (to match what the above version of Jira uses)
* AMPS: ⇒ 8.0.3 (and change `maven-jira-plugin` to `jira-maven-plugin`)
* `atlassian-plugins-osgi-testrunner`: ⇒ 2.0.1
* `jacoco-maven-plugin` ⇒ 0.8.5

**Comment by andrewswan** [comment]
I tried doing the above updates myself, but ran into this error:
```
(... Jira starts, wired test runs OK ...)
[INFO] [talledLocalContainer] Tomcat 8.x is stopped
[INFO] amps:stop in 18s
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.5:dump (dump-data) @ jira-jacoco-example ---
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] Connection refused (Connection refused)
[INFO] Connecting to localhost/127.0.0.1:6300
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:40 min
[INFO] Finished at: 2020-02-14T09:48:04+11:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:dump (dump-data) on project jira-jacoco-example: Unable to dump coverage data: Connection refused (Connection refused) -> [Help 1]
```
Is the problem that the TCP port used by JaCoCo closes when Jira shuts down?

**Comment by cristianonicolai** [comment]
@andrewswan thanks, I've fixed it locally, would you mind trying https://github.com/cristianonicolai/jira-jacoco-example/pull/2
